fix

diff --git a/bashible b/bashible
--- a/bashible
+++ b/bashible
@@ -8,12 +8,10 @@ ble_version() {
   echo 0.2
 }
 
-### INTERNAL FUNCTIONS ####
-
 ble_help() {
   echo "bashible version $(ble_version)"
   echo
-  echo "usage: bashible ./script.ble"
+  echo "usage: bashible ./script.bash"
   echo
   echo "see also: https://github.com/mig1984/bashible"
   echo
@@ -22,12 +20,6 @@ ble_help() {
   echo "  43   means halt (it stops execution also in parental scripts)"
   echo "  143  when terminated by TERM, QUIT, INT or HUP"
   echo
-  ble_exit 1
-}
-
-ble_exit() {
-  _FINISHED=1
-  exit $1
 }
 
 ble_print_start() {
@@ -52,6 +44,15 @@ ble_print_finish() {
 
 ble_print_continues() {
   echo -e "\033[1;37;45m ${_BLE_NAV} \033[1;37;44m ... \033[0m\n" >&2
+}
+
+ble_cd_basedir() {
+  cd "${_BASE_DIR}" || fail "can't enter base dir '${_BASE_DIR}'"
+}
+
+ble_exit() {
+  _FINISHED=1
+  exit $1
 }
 
 ble_do_finish() {
@@ -86,19 +87,29 @@ ble_trap_termination(){
     " SIGHUP SIGINT SIGQUIT SIGTERM
 }
 
-ble_serialize_command() {
-  oldIFS=$IFS
-  IFS=$'\t'; echo -e "$PWD\t$*"
-  IFS=$oldIFS
+ble_set_nav_and_level() {
+  let _BLE_LEVEL=${_BLE_LEVEL}+1
+  if test ${#_BLE_NAV} -eq 0 ; then
+    _BLE_NAV="`basename ${_SCRIPT_PATH} | sed "s/\.bash\$//" `"
+  else
+    _BLE_NAV="${_BLE_NAV} -> `basename ${_SCRIPT_PATH} | sed "s/\.bash\$//" `"
+  fi
 }
 
 ble_check_cmd() {
   quiet type "$1" || fail "command '$@' not found (CWD is $PWD)"
 }
 
+ble_run_script() {
+  ble_print_start
+  _FINISHED=0
+  source "$1"
+  # unless it gets here, unhandled exit happened -> the exit handler will react on it because _FINISHED will be still set to 0
+  _FINISHED=1
+}
+
 ble_handle_failure() {
- local ex=$1
- shift
+ local ex=$1; shift
  if ((ex>0)); then
    if ((ex!=42 && ex!=43)); then
      fail "command '$@' failed with exit code $ex (CWD is $PWD)"
@@ -108,11 +119,17 @@ ble_handle_failure() {
  fi
 }
 
+ble_serialize_command() {
+  oldIFS=$IFS
+  IFS=$'\t'; echo -e "$PWD\t$*"
+  IFS=$oldIFS
+}
+
 ### CORE FUNCTIONS ###
 
 @() {
   _SKIP=0
-  cd "${_BASE_DIR}" || fail "can't chdir to base dir '${_BASE_DIR}'"
+  ble_cd_basedir
   ble_print_block "$*"
 }
 
@@ -162,24 +179,7 @@ base_dir() {
   if test ${#_BASE_DIR} -eq 0; then
     fail "base_dir: absolute_path '$1' failed"
   fi
-  cd "${_BASE_DIR}" || fail "can't chdir to base dir '${_BASE_DIR}'"
-}
-
-ble_run_script() {
-  ble_print_start
-  _FINISHED=0
-  source "$1"
-  # unless it gets here, unhandled exit happened -> the exit handler will react on it because _FINISHED will be still set to 0
-  _FINISHED=1
-}
-
-ble_set_nav_and_level() {
-  let _BLE_LEVEL=${_BLE_LEVEL}+1
-  if test ${#_BLE_NAV} -eq 0 ; then
-    _BLE_NAV="`basename ${_SCRIPT_PATH} | sed "s/\.ble\$//" `"
-  else
-    _BLE_NAV="${_BLE_NAV} -> `basename ${_SCRIPT_PATH} | sed "s/\.ble\$//" `"
-  fi
+  ble_cd_basedir
 }
 
 call() {
@@ -190,7 +190,8 @@ call() {
      ble_trap_termination
      ble_trap_exit
      set -eu -o pipefail +m
-     ble_run_script "$@"
+     local name=$1; shift
+     ble_run_script "$name".bash "$@"
   )
   local ex=$?
   if ((ex>0)); then
@@ -220,7 +221,7 @@ empty() {
 }
 
 evaluate() {
-  eval "$@" || return $?  # || is here to bypass the pipefail exit
+  eval "$@" || return $? # || bypasses pipefail
 }
 
 fail() {
@@ -241,10 +242,8 @@ finish() {
   ble_exit 0
 }
 
-
 fill_var() {
-  local var=$1
-  shift
+  local var=$1; shift
   ble_check_cmd "$1"
   local buf
   buf=` "$@" || return $? ` || ble_handle_failure $? "$@"
@@ -273,12 +272,11 @@ not() {
 }
 
 output_to() {
-  local dest=$1
-  shift
+  local dest=$1; shift
   test "${#dest}" -gt 0 || fail "output_to: no destination file specified"
   ble_check_cmd "$1"
   local ex=0
-  "$@" | tee $dest.tmp || ex=$?  # || bypass pipefail error
+  "$@" | tee $dest.tmp || ex=$? # || bypasses pipefail
   if test $ex -eq 0; then
     mv "$dest.tmp" "$dest"
   else
@@ -308,16 +306,14 @@ quiet() {
 }
 
 reset_base_dir() {
-  _BASE_DIR=${_ORIG_BASE_DIR}
-  cd "${_BASE_DIR}"
+  base_dir "${_ORIG_BASE_DIR}"
 }
 
 result() {
-  local name=$1
-  shift
+  local name=$1; shift
   ble_check_cmd "$1"
   local ex=0
-  "$@" || ex=$? # || is here to bypass pipefail exit
+  "$@" || ex=$? # || bypasses pipefail
   eval "$name() {
     if test \$# -gt 0; then
       test \"$ex\" \"\$@\"; # with arguments
@@ -342,12 +338,11 @@ var_empty() {
 
 when() {
   _WHEN_USED=1
-  "$@" || return $?  # || is here to bypass the pipefail exit
+  "$@" || return $? # || bypasses pipefail
 }
 
 unless_already() {
-  local cmd=$1
-  shift
+  local cmd=$1; shift
   local path=`absolute_path "$cmd"`
   local scmd=`ble_serialize_command "$path" "$@"`
   if ! grep -q "$scmd" < ${_BLE_ALREADY}; then
@@ -384,7 +379,7 @@ _BLE_NAV=${_BLE_NAV}
 _BLE_ALREADY=${_BLE_ALREADY}
 _BLE_DELAYED=${_BLE_DELAYED}
 
-# now we can set defaults to be strict, will use a new process group
+# now we can set defaults to be strict & use a new process group
 set -eu -o pipefail -m
 
 _ORIG_DIR=` pwd `
@@ -393,18 +388,16 @@ test ${#_BLE} -gt 0 || fail "can't get _BLE; is 'readlink' command present?"
 _BLE_DIR=` dirname "${_BLE}" `  # bashible modules reside there
 test ${#_BLE_DIR} -gt 0     || fail "can't get _BLE_DIR; is 'dirname' command present?"
 test ` basename "${_BLE}" ` = bashible || fail "the 'basename' command is probably not present"
-_SCRIPT_PATH=`absolute_path "$1"`
-shift
+_SCRIPT_PATH=`absolute_path "$1"`; shift
 base_dir "`dirname "${_SCRIPT_PATH}"`"
 _ORIG_BASE_DIR=${_BASE_DIR}
 _BLE_SUBSHELL_PID=0
-
-cd "${_BASE_DIR}" || fail "can't enter base dir '${_BASE_DIR}'"
 
 _SKIP=0                      # skipping mode? will be reset on a next block
 _WHEN_USED=0                 # "-" will set skipping mode depending on the final result
 _FINISHED=0                  # to detect unhandled exits (pipefail)
 
+ble_cd_basedir
 ble_set_nav_and_level
 ble_trap_termination
 ble_trap_exit_top
